Ледянкин Павел
kontur-courses/clean-code pull request #129
Opened 2021-11-17 09:06 UTC by PavelLediankin

2021-11-18 03:21 UTC, orange-bird commented on cs/Markdown/Md.cs
> +            //Concat
Что будет делать `Concat`? Кажется, что `ToHtml` уже должно возвращать html-разметку без необходимости их соединения по непонятным снаружи правилам - html-конвертер эту логику уже должен содержать внутри.

2021-11-18 03:21 UTC, orange-bird commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
Может, лучше `IEnumerable`? Тут нет необходимости в получении коллекции целиком до того, как с ней будут производиться какие-то практические действия.

2021-11-18 03:21 UTC, orange-bird commented on cs/Markdown/Token.cs
> +        public virtual string ToHtml()
Я бы предложил смотреть на токены как на сущность, не зависящую от конечного формата. Html - это один из вариантов представления. Если уж преобразовывать токены в html, то с использованием отдельного класса, который умеет делать именно это.

2021-11-18 03:21 UTC, orange-bird commented on cs/Markdown/Token.cs
> +        protected string EscapeSymbols(string text)
Этот метод предполагается сделать обязательным? Если да, то лучше не давать полностью переопределять вызывающий метод `ToHtml()`, чтобы "реализации" токенов не могли случайно "забыть" про вызов этого метода.

2021-11-18 03:21 UTC, orange-bird commented on cs/Markdown/Token.cs
> +        public readonly string Value;
Что будет записано в `Value` для токена, обозначающего выделение курсивом, в таком случае: `<italic><bold>some text</bold></italic>`? Обязательно ли это значение для абсолютно всех токенов?

2021-11-18 12:55 UTC, PavelLediankin commented on cs/Markdown/Md.cs
> +            //Concat
Я предполагаю, что будут возвращаться токены, каждый из которых оборачивается в html, а полученные строки можно просто сложить (Насколько я помню Concat для этого и нужен)

2021-11-18 13:02 UTC, PavelLediankin commented on cs/Markdown/Token.cs
> +        public virtual string ToHtml()
Не уверен, тогда в этом классе придется либо создавать отдельные методы под разные токены, либо внутри определять токены, а потом уже создавать html-разметку.
В этом случае каждый токен в зависимости от его типа будет конвертиться в html и способ будет определяться непосредственно в типе разметки (курсив, абзац...)
А то что такой подход несколько усложнит добавление другого формата, конечно не очень хорошо, но учитывая что в этой задаче вряд ли появится такая необходимость - некритично

2021-11-18 13:05 UTC, PavelLediankin commented on cs/Markdown/Token.cs
> +        protected string EscapeSymbols(string text)
не давать полностью переопределять вызывающий метод  - Это возможно ?
Я бы в таком случае сделал свойство или вызывал метод в конструкторе

2021-11-18 13:10 UTC, PavelLediankin commented on cs/Markdown/Token.cs
> +        public readonly string Value;
У предполагаю сделать это таким образом для вложенных токенов - value - либо пусто, либо сырой текст.
И здесь начинает играть роль InnerValue - это будет выглядеть примерно так:
Token(itallic), Strong(some bold itallic text), 
Просто токен - возвращает экранированную строку, стронг будет обернут в bold, и все это обернуто в  italic

2021-11-18 13:13 UTC, PavelLediankin commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
Думаю это возможно, тогда текст будет возвращаться по абзацам и это наверно даже неплохо для большого текста, но такой подход меня слегка смущает, мне проще вернуть полностью готовый результат,
Впрочем если IEnumerable действительно лучше - то могу попробовать с ним

2021-11-18 13:14 UTC, PavelLediankin commented on cs/Markdown/Md.cs
> +            //Concat
То есть никаких сложных правил соединения не будет, грубо говоря += в цикле по токенам

2021-11-18 14:26 UTC, orange-bird commented on cs/Markdown/Md.cs
> +            //Concat
А почему это тогда не сделать внутри конвертера в html? Почему это где-то отдельно и полагается на то, что в html можно получить объединение, просто соединив строки? Теоретически, если бы это был не html, а что-то другое с другими правилами слияния, то Concat мог бы работать по-другому.

2021-11-18 14:28 UTC, orange-bird commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
Проще - не всегда лучше.
Например, если парсер будет работать последовательно и, если переходить на техническую сторону, использовать yield, то потребитель может в любой момент остановиться в перечислении и парсер не будет обрабатывать все. В случае больших файлов на больших объемах преобразований это может дать существенный выигрыш в производительности.

2021-11-18 14:29 UTC, orange-bird commented on cs/Markdown/Token.cs
> +        public virtual string ToHtml()
Мы же делаем расширяемое решение, нет? :)
Логично разделить его так, чтобы дальнейшая модификация не приносила боль и страдания. Тем более, кажется, это не треует сильного изменения логики.

2021-11-18 14:31 UTC, orange-bird commented on cs/Markdown/Token.cs
> +        protected string EscapeSymbols(string text)
Что может быть проще.
```
private void Do()
{
  DoRequiredThings();
  DoNonRequiredThings();
}
private void DoRequiredThings() {}
protected abstract void DoNonRequiredThings();
```

2021-11-18 15:06 UTC, PavelLediankin commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
+

2021-11-18 15:08 UTC, PavelLediankin commented on cs/Markdown/Token.cs
> +        protected string EscapeSymbols(string text)
понял

2021-11-18 15:10 UTC, PavelLediankin commented on cs/Markdown/Token.cs
> +        public virtual string ToHtml()
Хорошо, тогда выделю класс и отправлю на ревью

2021-11-18 15:30 UTC, PavelLediankin commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
У меня в процессе возник вопрос - предполагается что результатом должна быть разметка,
Мы в процессе берем токены из парсера по одному и по одному обрабатываем в Конвертере.
Но возвращать нам нужно сразу всю разметку а не сначала заголовок, потом абзац 1, ....
Тогда либо нам не нужно останавливать перечисление(значит оно нам не нужно),
 либо конвертер выдаст некорректный результат.
 
 Или использовать IEnumerable  а потом ToList -> Converter ?

2021-11-19 04:39 UTC, orange-bird commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
Тут конвертер решает, когда остановиться и нужно ли это делать.
То есть `IEnumerable<Token>` используется конвертером, который выдает итоговый результат `string`. Но при этом, если ему что-то не нравится - ошибка или не подходит по другим условиям - он может обработать часть токенов, а остальные даже не будут на момент остановки созданы.

2021-11-19 04:41 UTC, orange-bird commented on cs/Markdown/Parser.cs
> +        public List<Token> Parse(string mdText)
Как практический вариант подобного: представь, что на входе - большой markdown-файл. Его нужно в потоковом режиме обработать, а потом в потоковом режиме записать на диск в виде файла. Тут нет строки на вход и строки на выход. Есть потоки чтения и записи, которые в обратную сторону не работают и не умеют читать все сразу, т.к. объемы большие.

2021-11-25 05:55 UTC, orange-bird requested changes

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +            return sb.Length > 2 ?
Странное на вид условие. Почему 2? Зачем тут что-то обрезать?

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +                    return TokenToHtml(t);
Очень странно выглядят одинаковые вызовы для каждого условия. В данном случае проще было не создавать отдельные `TokenToHtml` для каждого типа токенов, а объединить их одним методом. Исходя из текущей реализации, они все в том или ином вызывают `DecorateWithTag`. Если унаследовать html-реализации токенов от условного `DecoratedTagToken`, то внутри него будет одна и та же реализация.

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +            => DecorateWithTag(token, "strong", "__");
У нас есть токен для выделения жирным шрифтом. Есть понимание, что для выделения в html используется тег strong. Зачем тут "__"? Оно не относится к конвертеру в html. Оно было парой этапов раньше в парсере markdown-разметки.

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +                token.InnerTokens.Last().Value.Last() : 'X';
Что такое 'X'?

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +                        continue;
Форматирование не то

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +using System.Collections;
Неиспользуемые using нужно удалять

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/Md.cs
> +                .ToList());
Зачем тут `ToList()`, особенно учитывая, что конвертеру внутри он тоже не нужен?

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/Parser.cs
> +    public class Parser
Закомментированного текста не должно оставаться в конечном решении. Если этот код нужен, он должен работать. Если не нужен, то нужно его удалить. В конце концов, есть git, в нем можно в одной из ревизий сохранить старый вариант, если он был актуален.

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/StringExtensions.cs
> +    public static class StringExtensions
Лучше такие штуки делать `internal`, чтобы они не мешали тем, кто будет использовать эту библиотеку.

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/Token.cs
> +    public class Header : Token
Все классы желательно разделять в разные файлы.

2021-11-25 05:55 UTC, orange-bird commented on cs/MarkdownTest/MdTests.cs
> +using FluentAssertions;
using перечислены не по порядку. Обычно используется алфавитный порядок с приоритетом у System. То есть в данном случае 
```
using System;
using System.Collections.Generic;
using FluentAssertions;
using Markdown;
using NUnit.Framework;
```

2021-11-25 05:55 UTC, orange-bird commented on cs/MarkdownTest/MdTests.cs
> +        //[TestCase("В то же время выделение в ра_зных сл_овах не работает",
Не работает? :)

2021-11-25 05:55 UTC, orange-bird commented on cs/MarkdownTest/MdTests.cs
> +    public class TestHelper
Вроде бы не используется. Зачем это тут?

2021-11-25 05:55 UTC, orange-bird commented on cs/Markdown/Markdown.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Лучше бы было выделить все, что касается Markdown, в отдельный solution.

2021-11-25 05:55 UTC, orange-bird commented on cs/MarkdownTest/MdTests.cs
> +        public void SetUp()
Зачем пустой метод?

2021-11-25 05:55 UTC, orange-bird commented on cs/MarkdownTest/MdTests.cs
> +    public class MdShould
Не увидел теста на линейную сложность

2021-11-25 07:37 UTC, PavelLediankin commented on cs/Markdown/HtmlConverter.cs
> +            return sb.Length > 2 ?
После каждого абзаца добавляется \r\n, видимо хотел удостоверится что эти два символа есть, но эта проверка действительно не нужна

2021-11-25 07:40 UTC, PavelLediankin commented on cs/Markdown/HtmlConverter.cs
> +            => DecorateWithTag(token, "strong", "__");
В некоторых случаях используется альтернативный тэг, проверить нужно ли его оставить или нет в парсере наверное возможно, но сложно, тем более этот класс итак переусложнен, так что  итоговые проверки, какой тэг использовать я вынес сюда

2021-11-25 10:09 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +            return sb.Length > 2 ?
Зачем вообще эти `\r\n` в html?

2021-11-25 10:11 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +            => DecorateWithTag(token, "strong", "__");
Не, так не работает. Парсер должен определять, какие токены нужно создать вместо markdown-разметки. А затем, уже не возвращаясь к парсеру и забыв про правила markdown, нужно просто сконвертировать готовые токены в html.

2021-11-25 10:12 UTC, orange-bird commented on cs/Markdown/HtmlConverter.cs
> +                        continue;
Вообще, я скорее про явно выбивающийся из ряда `continue` писал.

2021-11-25 11:16 UTC, orange-bird approved these changes

2022-11-01 05:44 UTC, closed without merging