Бухарский Максим
kontur-courses/clean-code pull request #152
Opened 2022-11-16 01:14 UTC by Seekard

@HELLoWorlD01100

2022-11-19 11:51 UTC, HELLoWorlD01100 requested changes
Общая идея понятна. 
Но как будет выглядеть реализация пока не очень понятно.

Также вкину сразу на подумать, т.к вижу, что решил стак использовать: в твоём решении норм обработается кейс __abc_qwerty__?

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Symbols.cs
> +        public static bool IsMarkdownSymbol(string symbol)
Добавление символа потребует добавление в двух местах.

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Validator.cs
> +public class Validator
Давай более подробное название.

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Symbols.cs
> +        public static readonly string EscapeSymbol = @"\";
Зачем это торчит наружу?

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Symbols.cs
> +            return symbol == ItalicSymbol || symbol == BoldSymbol || symbol == HeaderSymbol || symbol == EscapeSymbol;
А если 100 символов решим поддерживать, у нас во сколько строк это будет?

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/TextSegment.cs
> +public class TextSegment
Чем это отличается от обычного SB?)
Тоже вижу методы по добавлению строки, сложению sb(этого просто можно добиться), toString().

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/TextSegment.cs
> +        public void AddInnerSegment(TextSegment segment)
А можешь рассказать как это будет работать и что значит InnerSegment? Как будем понимать как внутрь вставить? На какую позицию и тд

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Validator.cs
> +    public bool IsEscapeSymbolBeforeMarkdownSymbol(string text, int indexOfEscapeSymbol)
кмк хватило бы метода приватного для такой проверки

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Tags.cs
> +        public readonly string ItalicTag = "<em>";
Константы

2022-11-19 11:51 UTC, HELLoWorlD01100 commented on cs/Markdown/Symbols.cs
> +        public static readonly string ItalicSymbol = "_";
Константы

2022-11-20 14:02 UTC, Seekard commented on cs/Markdown/Tags.cs
> +        public readonly string ItalicTag = "<em>";
Я хотел сделать readonly, чтобы можно было подгружать тэги из конфига (или просто передавать в конструктор)

2022-11-20 14:02 UTC, Seekard commented on cs/Markdown/Validator.cs
> +    public bool IsEscapeSymbolBeforeMarkdownSymbol(string text, int indexOfEscapeSymbol)
Поддерживаю)

2022-11-20 14:06 UTC, Seekard commented on cs/Markdown/TextSegment.cs
> +public class TextSegment
В нем есть метод Render, который обрабатывает как внутренние сегменты, так и сам сегмент. Если использовать sb, то не получиться нормально реализовать обработку внутренних сегментов.

2022-11-21 12:29 UTC, HELLoWorlD01100 requested changes
Не работает/работает неправильно:
- \_abc \_\_de\_\_ q\_
- \# abcq
- ___abc___
- __a_bc___
- _ab__cd_
Это то, что сходу придумал, наверняка есть еще.

Решение нерасширяемо. Посмотри, например, на спецификацию ссылки. Как мы вклиним ее сюда?

2022-11-21 16:02 UTC, Seekard commented on cs/Markdown/Md.cs
> +                segment = HandleUnderlineSymbol(segmentsStack, segment, symbol, text, ref i);
Оба передают аргмент по ссылке.
В out можно изначально не инициализировать объект, который передаешь.
Отсюда следует, что out всегда должен инициализовать out аргументы.

2022-11-21 18:00 UTC, HELLoWorlD01100 commented on cs/Markdown.Tests/MdTests.cs
> +    public class MdTests
То, что можно, я не отрицаю. Выглядит странно просто. И напоминает 1С :)

Каких-то резких "против" я не вижу.

2023-11-23 04:55 UTC, closed without merging