Ясиновский Александр
kontur-courses/clean-code pull request #161
Opened 2022-11-18 14:16 UTC by Alex2021cyberhuman

reviewer: @coffee-and-problems

2022-11-18 14:17 UTC, Alex2021cyberhuman commented
п. 1. 
Проведи начальное проектирование: зафиксируй классы и их методы в коде (а также связи между классами), но не пиши внутренности методов
п. 2.
Покажи декомпозицию наставнику, получи обратную связь

2022-11-18 14:18 UTC, Alex2021cyberhuman commented
что то я затянул с домашкой. постараюсь исправиться.

2022-11-18 16:05 UTC, coffee-and-problems requested changes

2022-11-18 16:34 UTC, Alex2021cyberhuman commented on cs/Markdown/Md.cs
> +public abstract class MdState
это база, я знаю. это я на показ оставил.

2022-11-18 16:47 UTC, Alex2021cyberhuman commented on cs/Markdown/Md.cs
> +public abstract class MdToken
я считаю что хорошо бы оставить точку расширения  в виде различных токенов, что бы иметь возможность добавить разные форматы экспорта

2022-11-18 16:47 UTC, Alex2021cyberhuman commented on cs/Markdown/Md.cs
> +public abstract class MdToken
кроме хтмл

2022-11-18 16:57 UTC, coffee-and-problems commented on cs/Markdown/Md.cs
> +public abstract class MdToken
Т.е. это токен для html только? Что такое этот токен, что он будет представлять из реального мира? Почему не интерфейс (всегда можно создать новую реализацию для другого языка), почему не моделька (ее всегда можно методами расширения расширить, или на крайний случай там уже заиспользовать наследование). Какие преимущества у абстрактного класса перед другими вариантами?

2022-11-21 07:59 UTC, coffee-and-problems requested changes

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/IMdMarkupTokenParser.cs
> +public interface IMdMarkupTokenParser
Мне кажется такое название не очень очевидным, обычно подобные сборные парсеры у нас называют со словом Composite - `IMdCompositeTokenParser`. Если не нравится, как это звучит, можно еще попробовать `IMdToken**s**Parser` - чтобы подчеркнуть, что он именно коллекцию токенов парсит, а не один конкретный

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/MdHtmlBoldParser.cs
> +public class MdHtmlBoldParser : IMdTokenParser
Мне нравится, как ты выделил здесь парсеры: есть конкретные парсеры для каждого типа токенов, реализующую общий интерфейс, и есть композитный парсер, который будет выполнять роль оркестратора для конкретных парсеров. Это хороший, легко расширяемый подход

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/MdHtmlBoldParser.cs
> +        return token.Type == MdTokenType.Bold && token is MdBoldTextToken;
Класса `MdBoldTextToken` нет в репозитории

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/MdHtmlMarkupTokenParser.cs
> +        this.parsers = parsers ?? new Dictionary<MdTokenType, IMdTokenParser>
Тут можно не строить новый словарь, он же уже приходит в параметре конструктора `parsers`. Это избавит от главной проблемы этого конструктора - циклической зависимости в парсерах

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/MdHtmlMarkupTokenParser.cs
> +            { MdTokenType.Header, new MdHtmlHeaderParser(this) },
Вот тут вот циклическая зависимость

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/MdTextContainerToken.cs
> +public abstract class MdTextContainerToken : MdToken
Обсудили в тг, что тут хотелось разделить на контейнеры (\<p>, \<h1>) и текст (\<strong>, \<em>)  так как первые могут содержать только вторые, а вторые не могут содержать никого (strong может содержать курсив).
Все еще считаю, что это можно сделать более красиво без цепочек из наследников - по сути то нам интересно лишь знание о том, какие теги внутри себя может содержать тег. Мое предложение такое: можно в MdToken добавить хешсет (или список, или массив, как удобнее) из типов тегов (уже описанных в MdTokenType), которые этот тег может содержать внутри себя. Если этот сет пуст - значит никакие теги не может содержать

2022-11-21 07:59 UTC, coffee-and-problems commented on cs/Markdown/MdTextContainerToken.cs
> +public abstract class MdTextContainerToken : MdToken
Зафиксирую еще аргументы, почему хочется избавиться от цепочки наследованных классов:
1. Наследование сильно связывает код. Наследник уже не самостоятельная сущность и не может существовать отдельно от родителя - следовательно, она тяжелее поддается изменению и переиспользыванию, а это одни из главных китов в ООП.
2. Нельзя, посмотрев на класс, сразу увидеть все, что он делает. Нужно туда-сюда переходить от наследника к родителю и обратно, чтобы составить полную картину.
3. По SRP у каждого класса должна быть своя зона ответственности. Наследование - это расширение зоны ответственности. Т.е. наследник уже всегда содержит всю зону ответственности родителя. Мы же стремимся ЗО уменьшать, чтобы такой код было проще поддерживать.

2022-11-21 11:41 UTC, Alex2021cyberhuman commented on cs/Markdown/MdHtmlMarkupTokenParser.cs
> +            { MdTokenType.Header, new MdHtmlHeaderParser(this) },
не понимаю где зависимость, если только логическая циклическая, а как убрать не понимаю, передавать не ссылку на главный парсер, а словарь парсеров?

2022-11-21 11:50 UTC, Alex2021cyberhuman commented on cs/Markdown/MdTextContainerToken.cs
> +public abstract class MdTextContainerToken : MdToken
а все равно логика парсинга мд находится в сейтах, и уже разработчик стейта уж точно должен знать какие теги может содержать токен. токен просто хранилище для результата. в моем случае можно и по твоему пойти пути, но так можно забыть про заранее заданные ограничения, но конечно про них забыть не получится если написать тесты заранее по тдд, и тесты будут падать, а в моем случае при ошибочном занесении тега в тег в котором не может быть первый тег будет ошибка компиляции.

2022-11-21 12:30 UTC, coffee-and-problems commented on cs/Markdown/MdTextContainerToken.cs
> +public abstract class MdTextContainerToken : MdToken
> логика парсинга находится в стейтах

Почему в стейтах, а не в парсерах?

> и уже разработчик стейта уж точно должен знать какие теги может содержать токен.

Оставлять правила и ограничения на знания разработчику - это плохой подход в промышленном программировании. Разработчики увольняются, забывают информацию, а этот код должно быть просто поддерживать и через 10 лет. Код сам должен хранить (инкапсулировать) в себе свои правила

> но так можно забыть про заранее заданные ограничения

Какие ограничения?

> написать тесты заранее по тдд, и тесты будут падать

Тесты все же пишутся после этапа проектирования решения, хотя и до реализации логики в классах. Наша дискуссия тут за проектирование, на этом этапе тестов еще не существует

2022-11-21 12:47 UTC, coffee-and-problems commented on cs/Markdown/MdHtmlMarkupTokenParser.cs
> +            { MdTokenType.Header, new MdHtmlHeaderParser(this) },
Чтобы построить MdHtmlHeaderParser тебе нужно построить MdHtmlMarkupTokenParser, а чтобы построить MdHtmlMarkupTokenParser тебе нужно построить MdHtmlHeaderParser. Это называется "циклическая зависимость". У вас должен быть еще модуль про DI (dependency injection) контейнеры, там подробно расскажут, почему это называется зависимостью, и почему подобный код может развалиться на старте приложения

2022-11-21 14:00 UTC, Alex2021cyberhuman commented
разбирает поток символов на токены, а потом токены собирает в html разметку 
.

2022-11-21 14:07 UTC, Alex2021cyberhuman commented
я просто вообще не понимаю как надо правильно

2022-11-21 14:28 UTC, coffee-and-problems commented
Давай чуть более подробно и по шагам, как будто ты алгоритм описываешь. "Разбивает поток символов на токены" - что такое токены? Код идет последовательно по символам и добавляется их куда-то? Что скрывается под "собирает" в html разметку? В какой момент будут проверки на вложенные тэги или на экранирование?

> я просто вообще не понимаю как надо правильно 

у задачи много решений, скорее всего ты всё правильно придумал и это будет в итоге работать. Проблема в том, что я никак не могу понять, что именно ты придумал, и я задаю вопросы (например, что такое токен в его разных вариациях, или что за состояние ты выделил) которые остаются без ответа. Поэтому сейчас хочу понять само решение, и уже отталкиваясь от этого мы можем вместе подумать, как его обернуть в код

2022-11-21 14:46 UTC, Alex2021cyberhuman commented
a) что такое токены
токены - абстрактные элементы разметки
b) код не обязательно идет последовательно, состояние может создать другое состояние и скопировать в него последовательность предыдущих символов, но в общем случае - да последовательно.
с) ...

2022-11-22 09:56 UTC, Alex2021cyberhuman commented
хотел сделать по типу fsm

2022-11-22 11:49 UTC, coffee-and-problems commented
Ок, описание, как это решение будет работать, я не услышала, если честно( Только концепцию и отсылку на стейт-машину, хотела услышать, как будет выполняться код, как ты в своей голове представляешь его работу.
Доводи решение до финала и пингани в тг, пожалуйста, как можно будет посмотреть

2022-11-27 06:54 UTC, Alex2021cyberhuman commented
Я спрашивал у тебя, Мария, про продление дедлайна, но ты сказала что утром можно отправить и проблем не будет тк сможешь проверить только в пн. Вот фиксирую это в пулл реквесте. Мое решение это тоже fsm,  я думаю, только переходы между состояниями вынесены в отдельные модули.

Сделал как в tag cloud вывод лога для диагностики если тест упал

Сделал еще тест на линейность, который что бы запустить, нужно выполнить команду (запуск в релиз конфигурации, для оптимизаций)
`dotnet test --filter "Name=Render_OofNDifficulty_ShortAndLongMarkdown" --configuration RELEASE`

2022-11-28 07:06 UTC, coffee-and-problems approved these changes

2022-11-28 07:18 UTC, coffee-and-problems commented
Еще нужно было добавить описание, как работает дополнительный тег (список в твоем случае) в фале спецификации  [clean-code](https://github.com/kontur-courses/clean-code)/MarkdownSpec.md

2022-11-28 07:23 UTC, Alex2021cyberhuman commented on cs/Markdown.UnitTests/MdTests.cs
> +        shortPartInLongMd.Should().BeLessOrEqualTo(shortNanoseconds);
Или меньше чем время затраченное на обработку малого объема + 10%

2023-11-23 04:55 UTC, closed without merging