Кусый Максим
kontur-courses/clean-code pull request #96
Opened 2020-11-09 15:47 UTC by PShenica

@fng3r

2020-11-12 18:51 UTC, fng3r requested changes

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown.Tests/HtmlConverterTests.cs
> +
как то тут пустовато, однако

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown.Tests/HtmlConverterTests.cs
> +
как будто бы даже и тдд не использовалось

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown.Tests/MarkdownTests.cs
> +    }
![image](https://user-images.githubusercontent.com/18289223/98979383-1de96580-253d-11eb-9b66-6aeca70ac709.png)

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown.Tests/TextParserTests.cs
> +        private TextParser Sut { get; set; }
это ж парсер, почему он сталом sut'ом?

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown.Tests/TextParserTests.cs
> +        static object[] TestCases =
я понимаю, почему ты засунул все тесты в один test case source (потому что код теста всегда один и тот же), но делать так крайне не рекомендую
стоит объединять тесты, которые как-то связаны (например, различные кейсы для определенного тега, и то не факт, что нужно, зависит от того, что там именно тестится), иначе ты получаешь вот такой монструозный метод, в котором еще потом копаться придется, когда тест упадет, чтобы найти нужный кейс

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/HtmlGenerator.cs
> +    public class HtmlGenerator
не понял, зачем нужен этот класс, потом подумал еще раз, но все равно не понял
для чего нужно эта обертка над конвертером, которая, к тому же, еще ничего и не делает, кроме как дергает его одноименный метод? с таким же успехом можно еще один слой накрутить поверх генератора, который, в свою очередь, будет дергать уже генератор

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +                        result.Append(token.ValueWithoutTags());
сделай ты `var tokenValue = token.ValueWithoutTags()` один раз перед свитчем, зачем ты в каждом кейс дергаешь этот метод?

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +                        result.Append(token.ValueWithoutTags());
а еще вместо этой портянки можно завести маппинг `TokenType` -> `HtmlTagName`, и весь этот метод значительно упростится

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/IConverter.cs
> +        string CovertTokensToHtml(List<Token> tokens);
у тебя здесь получилась `leaky abstraction`
абтрактный конвертер, конечно же, не должен обладать знанием, что он конвертит что-то в хтмл

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/IConverter.cs
> +        string CovertTokensToHtml(List<Token> tokens);
тут еще опечатка (и еще где-то я видел), поставь себе ReSpeller, чтобы в будущем на это не отвлекаться

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/TokensGenerator.cs
> +    public class TokensGenerator
*коммент про хтмл генератор*

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/Token.cs
> +                TokenType.Strong => Value.Substring(2, Value.Length - 3),
здесь можно заипользовать рэнжи https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-8.0/ranges

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +        }
это логика вполне отделяема от парсера, можно ее унести в экстеншны

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                }
методы `FindSomething` унести в соответствующие `ITokenReader`ы, после чего код упростится +/- до
```
var token = readers
    .Select(reader => reader.TryReadToken(index))
    .First(tkn => tkn != null);
```
тут я использовал допущение, что ридеры уже как-то упорядочены по приоритету

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +        public Token FindStrongTag(int index, string text)
довольно странный порядок аргументов, я бы поменял

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +            }
это все можно заменить регексом, которые тебе все слеши найдет

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/Token.cs
> +        public int Lenght()
respeller, ага

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/Token.cs
> +        public int Lenght()
сделай это свойством, нет ни одной причины для того, чтобы это было методом

2020-11-12 18:51 UTC, fng3r commented on cs/Markdown/Token.cs
> +        public string ValueWithoutTags()
либо свойство, либо пусть содержит глагол в названии

2020-11-14 00:57 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +            }
окей, про регекс понял, мой косяк, но вот чего не понял, так это зачем ты хранишь словарь вместо списка позиций слешей?
помимо того, что это выглядит довольно странно, так это еще и крайне неэффективно (алгоритм на тексте из миллиона символов без слешей будет требовать O(n) дополнительной памяти, хотя она ему не нужна вообще)

2020-11-16 20:03 UTC, fng3r requested changes

2020-11-16 20:03 UTC, fng3r commented on cs/Markdown/TextParserExtensions.cs
> +                   && text[index - 1] != '_'
в этих строчках - `index - 1` - есть неплохой шанс словить `IndexOutOfRangeException`, кажется

2020-11-16 20:07 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +            return tokens;
это эквивалентно вызову `FindTokens`, так зачем нужно 2 метода?

2020-11-17 07:37 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                if (text[i] == '\\' && i + 1 < text.Length && text[i + 1] == '\\')
если за слэшом идет слэш, ты его просто проигноришь?

2020-11-17 08:45 UTC, fng3r commented on cs/Markdown/Token.cs
> +                }
а, ты его даже мутируешь тут, это точно лишнее, если токен должен быть плэйн тектсом, то он должен им быть сразу, а не менять свой тип на лету

2020-11-17 18:30 UTC, fng3r requested changes

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/StrongTokenReader.cs
> +                   && !new TextParser().IsAfterBackslash(text, index);
зависимость от парсера осталась, нужно от нее избавиться

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +        }
можно и так, конечно, но почему бы просто не принять `IEnumerable<Reader>` в конструктор? не совсем понимаю, для конвертера то же самое справедливо, кстати

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                    throw new ArgumentNullException();
1. тип ошибки тут некорректный, тут нет никакого аргумента
2. отсутствует сообщение, что мне делать с таким эксепшном, если я его поймаю?

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                .Where(x => x.Value != "")
странная фигня, если у токена внутри пусто, то почему это вообще валидный токен, который возвращается ридером?

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                token.Value = RemoveEscapingBackslashes(token);
почему это делается здесь, а не в момент, когда создается токен сразу с валидным значением? не вижу для этого причин

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                              && token.Type != TokenType.Strong);
опять возникают проверки на конкретный тип токена, тем самым ты снова лишаешь код свойства расширяемости, потому что как только появятся новые типы, их придется сюда дописывать

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                if (!IsNotDuplicatedToken(tokens, token))
а откуда вообще возникают дубли? я что-то не совсем понимаю
и почему ты добавляешь токен, если он задублировался?

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +        private static List<Token> ReplaceIntersectedTokens(List<Token> tokens, string text)
почему бы не детектить это во время чтения токенов, и, если там что-то пересекается, то просто не возвращать такие токены? тогда необходимость в этом пласте логики отпадет

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/TextParserExtensions.cs
> +        }
не вижу причин для того, чтобы это было экстеншнами, объясни

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/Token.cs
> +        }
токены не могут пересекаться, но это, опять же проблема того, что ты их сначала создаешь, а потом оказывается, что это вовсе не токены, потому что там что-то где-то пересеклось

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +                        continue;
тут тоже работа с конкретными типами, нужно выпилить

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/Token.cs
> +        public bool IsInsideToken(Token token)
почему ты отказался от концепции вложенных токенов и перешл вот на этот метод, который нужен исключительно для конвертации, в то время как дочерние токены имеют ценность сами по себе

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/ImageTagToken.cs
> +            var url = "";
почему бы тексту и урлу не быть дочерними токенами имэйдж токена? так у тебя получается, что конвертер занимается не конвертацией готового токена, а еще и на пол ставки парсером подрабатывает, хотя,  казалось бы, функции парсера должны быть уже выполнены этапом ранее

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/Markdown.cs
> +        public string Render(string markdown, ITextParser markdownParser, IConverter htmlConverter)
принимай зависимости в конструктор, нет смысла их каждый раз передавать в метод

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/Markdown.cs
> +        public string Render(string markdown, ITextParser markdownParser, IConverter htmlConverter)
и почему  абстрактный IConverter вдруг называется htmlConverter?

2020-11-17 18:30 UTC, fng3r commented on cs/Markdown/Markdown.cs
> +        public string Render(string markdown, ITextParser markdownParser, IConverter htmlConverter)
ITextParser markdownParser - переименуй либо класс, либо переменную

2020-11-17 18:40 UTC, fng3r commented on cs/Markdown/PlainTextTagToken.cs
> +            return token.GetValueWithoutTags();
откуда б у плэйн текста тегам взяться?

2020-11-21 10:31 UTC, PShenica commented
@fng3r

2020-11-21 15:26 UTC, fng3r requested changes

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +            }
как будто бы все это можно заменить на простой `.Where` и не использовать здесь стрингбилдер вообще

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/Token.cs
> +        public Token(int position, string value, int endPosition, TokenType type)
не хочешь отнаследоваться и сделать для каждого токена по классу с фиксированным значением типа? не придется каждый раз при создании токена вбивать его тип ручками (потенциальное место для того, чтобы ошибиться)

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +        private readonly Dictionary<TokenType, ITagTokenConverter> mapper = new Dictionary<TokenType, ITagTokenConverter>
эт не `mapper`, это `mapping` или `map`

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +        public void AddMapping(TokenType type, ITagTokenConverter tagTokenConverter)
для чего это метод нужен?

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +                    var newValue= ConvertTokens(token.ChildTokens);
используй клинап, плз, перед тем, как сдавать решение, в следующий раз предупреждением не ограничусь

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/HtmlConverter.cs
> +                    token.Value = newValue;
а вот здесь мутация состояния токена выглядит еще хуже
когда ты передаешь в метод список токенов, чтобы его сконвертировали во что-то еще, то точно не ожидаешь, что тебе эти самые токены подпортят в процессе

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +        public void AddTokenReaders(params ITokenReader[] tokenReaders)
а почему бы не взять и не принять список в токенов сразу в конструктор? а не фиксировать его и добавлять метод, чтобы его изменять

2020-11-21 15:26 UTC, fng3r commented on cs/Markdown/TextParser.cs
> +                        var newContext = text[token.Position..(token.EndPosition + 1)];
это разве не в точности `token.Value`?

2020-11-22 15:57 UTC, PShenica commented on cs/Markdown.Tests/EmphasizedTokenReaderTests.cs
> +        private EmphasizedTokenReader Reader { get; set; }
Так это свойство. Или можно ссыль на то, что ты имеешь в вид? И ide с клинапом ничего по этому поводу не говорят

2020-11-22 16:00 UTC, PShenica commented on cs/Markdown.Tests/HeadingTokenReaderTests.cs
> +        private HeadingTokenReader Reader { get; set; }
Нет

2020-11-24 13:44 UTC, fng3r requested changes

2020-11-24 13:44 UTC, fng3r commented on cs/Markdown.Tests/MarkdownTests.cs
>          private Markdown.Markdown Sut { get; set; }
sut :(

2020-11-24 13:44 UTC, fng3r commented on cs/Markdown.Tests/MarkdownTests.cs
> +        [TestCase(@"en_d._", @"en<em>d.</em>", TestName = "In word end")]
какой же это ад, побей эти кейсы хотя бы на несколько тестов со связанными кейсами, у этого мяса нулевая читабельность
бтв, уже обсуждали, вроде

2020-11-24 13:44 UTC, fng3r commented on cs/Markdown/TextParser.cs
>                          token!.ChildTokens.AddRange(childTokens);
`!` достаточно один раз заюзать, дальше компилятор уже знает, что здесь null не ожидается

2020-11-24 13:44 UTC, fng3r commented on cs/Markdown/IToken.cs
> +        public bool CanHaveChildTokens { get; }
а зачем ты заменил класс интерфейсом? профита я от этого не увидел никакого, зато теперь в каждом классе эта портянка свойств болтается

2022-11-01 05:45 UTC, closed without merging