Хамидуллина Аниса
kontur-courses/clean-code pull request #98
Opened 2020-11-09 19:26 UTC by catsAndSuicide

@goodoldlameme

2020-11-10 20:04 UTC, goodoldlameme approved these changes

2020-11-14 17:58 UTC, goodoldlameme requested changes

2020-11-14 17:58 UTC, goodoldlameme commented on cs/Markdown/MdToHTMLConverter.cs
> +                    elements.Remove(elementEndingInPtr[0]);
тут будет слишком много проходов по списку элементов вместе со всеми Where, OrderBy, тут можно попробовать хранить элементы в какой-нибудь более подходящей структурой данных, где поиск и удаление быстрее происходит

2020-11-14 17:58 UTC, goodoldlameme commented on cs/Markdown/MdTests.cs
> +        public void Md_ShouldNotRenderItalicStyle_InsideWordWithDigits(string mdtext, string expectedHtmlText)
еще можно проверить такие случаи:  `"te1xt _w1th_ nu1mbers", "_te1xt with nu1mbers_", "_12_ 3"`, теги должны работать, так как это вне текста с цифрами

2020-11-14 17:58 UTC, goodoldlameme commented on cs/Markdown/MdTests.cs
> +        [Test]
Давай обговорим как будут работать вот такого рода случаи: `___a___, ____a____, _____a_____` и т.д.
Сейчас они работают как-то так: `<strong>_a</strong>_, __<strong>a</strong>__, __<strong>_a</strong>___ `тем самым формально нарушая правило про пересечение тегов

2020-11-14 18:38 UTC, catsAndSuicide commented on cs/Markdown/Word.cs
> +        public bool IsInside(string tag, int tagPosition)
Здесь проверяется, что слово содержит тег (но не начинается на него и не заканчивается им)

2020-11-14 18:46 UTC, catsAndSuicide commented on cs/Markdown/ElementsFinder.cs
> +    internal static class ElementsFinder
То есть передавать в его конструктор вместе с текстом какую-то структуру, содержащую информацию о соответствии стилей и их finder'ов, о том, какие стили не могут содержаться в других и пересекаться с третьими?

2020-11-14 18:53 UTC, catsAndSuicide commented on cs/Markdown/MdTests.cs
> +        [Test]
Думаю, разумнее всего будет так:
- ___а___ = <strong><em>a</em></strong> (и для любого другого нечётного количества подчерков)
- ____а____ = <strong>a</strong> (и для любого четного количества подчерков)

2020-11-15 17:17 UTC, goodoldlameme commented on cs/Markdown/Word.cs
> +        public bool IsInside(string tag, int tagPosition)
тогда ContainsTag

2020-11-15 17:19 UTC, goodoldlameme commented on cs/Markdown/ElementsFinder.cs
> +    internal static class ElementsFinder
да, как-то так

2020-11-15 17:22 UTC, goodoldlameme commented on cs/Markdown/MdTests.cs
> +        [Test]
не поняла для четного количества символов почему один тег, может лучше `____а____ = <strong><strong>а</strong></strong>`?
Зафиксируй это тоже в спецификации рядом с спецификацией для доп. тега

2020-11-17 18:13 UTC, goodoldlameme approved these changes

2020-11-17 18:13 UTC, goodoldlameme commented on cs/Markdown/Converter/MdToHTMLConverter.cs
> +            this.comparer = comparer;
а если comparer не установят, а Convert вызовут?

2020-11-17 18:13 UTC, goodoldlameme commented on cs/Markdown/Converter/MdToHTMLConverter.cs
> +            this.comparer = comparer;
можно было решить этот вопрос прям в классе Token

2020-11-17 18:13 UTC, goodoldlameme commented on cs/Markdown/Finders/MdUnorderedListElementStyleFinder.cs
> +        public IEnumerable<Token> Find()
хорошо было бы декомпозировать, слишком много вложенных элементов вышло

2020-11-17 18:13 UTC, goodoldlameme commented on cs/Markdown/Finders/MdUnorderedListElementStyleFinder.cs
> +        private (int elementStart, int contentStart) GetNextUnorderedListElement()
в именованных кортежах лучше делать имена с большой буквы, чтобы нэйминг шарповый для публичных элементов не нарушать

2022-11-01 05:45 UTC, closed without merging